create table if not exists public.bazaar_snapshots (
  id bigint generated by default as identity primary key,
  product_id text not null,
  buy_order_price double precision not null,
  sell_offer_price double precision not null,
  spread double precision not null,
  margin_percent double precision not null,
  buy_volume bigint not null,
  sell_volume bigint not null,
  buy_moving_week bigint,
  sell_moving_week bigint,
  buy_orders integer,
  sell_orders integer,
  captured_at timestamptz not null
);

create index if not exists bazaar_snapshots_product_id_idx
  on public.bazaar_snapshots (product_id);

create index if not exists bazaar_snapshots_captured_at_idx
  on public.bazaar_snapshots (captured_at desc);

create index if not exists bazaar_snapshots_product_id_captured_at_idx
  on public.bazaar_snapshots (product_id, captured_at desc);

create unique index if not exists bazaar_snapshots_product_batch_unique_idx
  on public.bazaar_snapshots (product_id, captured_at);
